cxx_binary(
  name = 'basic',
  srcs = [
    'test_lest_basic.cpp',
  ],
  deps = [
    '//:lest',
  ],
)

cxx_binary(
  name = 'cpp03',
  srcs = [
    'test_lest_cpp03.cpp',
  ],
  deps = [
    '//:lest',
  ],
)

cxx_binary(
  name = 'decompose',
  srcs = [
    'test_lest_decompose.cpp',
  ],
  deps = [
    '//:lest',
  ],
)

cxx_binary(
  name = 'lest',
  srcs = [
    'test_lest.cpp',
  ],
  deps = [
    '//:lest',
  ],
)
