language: cpp
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
  homebrew:
    taps:
      - facebook/fb
    packages:
      - buck

os:
  - linux
  - osx

env:
  - BUCKAROO_VERSION=buckaroo-redux-alpha-11

osx_image: xcode9.3

before_install:
  - ./travis/before-install-$TRAVIS_OS_NAME.sh

script:
  - ./buckaroo-client install
  - buck build -c ui.superconsole=DISABLED //:lest
  - buck run -c ui.superconsole=DISABLED //test:basic
  - buck run -c ui.superconsole=DISABLED //test:cpp03
  - buck run -c ui.superconsole=DISABLED //test:decompose
  - buck run -c ui.superconsole=DISABLED //test:lest
